apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kanban
  name: kanban
spec:
  ports:
  - name: "81"
    port: 81
    targetPort: 80
  selector:
    io.kompose.service: kanban
status:
  loadBalancer: {}
