apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: main
  name: main
spec:
  ports:
  - name: "44304"
    port: 44304
    targetPort: 443
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: main
status:
  loadBalancer: {}
