apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: permissions
  name: permissions
spec:
  ports:
  - name: "82"
    port: 82
    targetPort: 80
  selector:
    io.kompose.service: permissions
status:
  loadBalancer: {}
