apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: reports
  name: reports
spec:
  ports:
  - name: "83"
    port: 83
    targetPort: 80
  selector:
    io.kompose.service: reports
status:
  loadBalancer: {}
